# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: æå®¢å…”å…”
keyword: geektutu,jiketutu,Goè¯­è¨€,golang,python
description: æå®¢å…”å…”çš„åšå®¢ï¼Œè‡´åŠ›äºåˆ†äº«ä¸€äº›æŠ€æœ¯æ•™ç¨‹å’Œæœ‰è¶£çš„æŠ€æœ¯å®è·µï¼ŒåŒ…æ‹¬ä½†ä¸é™äº Go è¯­è¨€/golang, Python, tensorflow, åˆ†å¸ƒå¼, æœºå™¨å­¦ä¹ ç›¸å…³çš„å†…å®¹ã€‚ä¹Ÿå¯ä»¥é€šè¿‡æœç´¢æå®¢å°ç«™,jiketutu æ‰¾åˆ°æˆ‘ã€‚
author: æå®¢å…”å…”
language: zh-CN

url: https://geektutu.com	
root: /
permalink: post/:title.html

# seoä¼˜åŒ–å„ä¸ªæµè§ˆå™¨çš„éªŒè¯ä¿¡æ¯
beian: æ²ªICPå¤‡18001798å·-1
seo_title: æå®¢å…”å…” # å­é¡µé¢çš„åç¼€ï¼Œæ•ˆæœï¼š å…³äºæˆ‘ | æå®¢å…”å…”ï¼Œå¦‚æœä¸titleä¸€è‡´ï¼Œåˆ™å¯ä»¥ä¸è®¾ç½®
seo:
  google_site_verification: X31OY0d2sKImNbS2x8-OpITWRK4nn7nZCcXe3_hA9ew
  baidu_site_verification: p7Pz3jlx4t
  ms_site_verification: 7E2AEE3378AC93764DEAB411177A21A1
  _360_site_verification: 1d1e81a1a48a1ed2e3308d7cb8e548e7 # ä¸èƒ½ä»¥æ•°å­—å¼€å¤´ï¼Œæ‰€ä»¥åŠ ä¸Šäº†ä¸‹åˆ’çº¿

# å¼€å¯åšå®¢èµ„æºçš„ç›¸å¯¹é“¾æ¥ https://hexo.io/zh-cn/docs/asset-folders
post_asset_folder: true 
skip_render: tool/comments.json
# Site settings
header_icon: img/icon.png

theme: geektutu

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://git.coding.net/gzdaijie/geektutu-blog.git
  branch: coding-pages

gitalk:
  client_id: 'c1fdd456a4caae5f7df0'
  client_secret: 'b2674451e21feae50520f99337ec15d2aebe7879'
  accessToken: '513dc2f1e6df8c07a12fbf1547874f54679d9712'
  repo: 'geektutu-blog'
  owner: 'geektutu'

# alipay wechatpay çš„äºŒç»´ç è½¬æ¢çš„ç½‘å€ï¼Œä¸ä½¿ç”¨äºŒç»´ç å›¾ç‰‡ï¼Œæé«˜åŠ è½½é€Ÿç‡ã€‚
reward:
  alipay: HTTPS://QR.ALIPAY.COM/FKX060337TUXBAX9LIFJE8
  wechat: wxp://f2f0qgGBlfD1nZXjvBjievxB0z0fc0W2sBq5

related_links:
- link: https://github.com/geektutu
  img: img/related_links/github.png
  name: Github
- link: https://zhuanlan.zhihu.com/geekgo
  img: img/related_links/go.png
  name: ä¸“æ 
- link: https://www.zhihu.com/people/gzdaijie
  img: img/related_links/zhihu.png
  name: çŸ¥ä¹
- link: https://weibo.com/geektutu
  img: img/related_links/weibo.jpg
  name: å¾®åš

# æ–‡ç« æœ«å°¾é…ç½®ä¸€äº›æç¤ºä¿¡æ¯ï¼Œå¯é€‰ï¼Œé»˜è®¤å…³é—­
post_tips:
  find_me: true # æœ¬ç«™æ°¸ä¹…åŸŸåã€Œ xx.domain ã€ï¼Œ ä¹Ÿå¯ä»¥é€šè¿‡æœç´¢ã€Œ xx ã€æ‰¾åˆ°æˆ‘ã€‚
  zhihu: https://www.zhihu.com/people/gzdaijie # æ¬¢è¿å…³æ³¨æˆ‘çš„ã€Œ çŸ¥ä¹ ã€ã€‚
  weibo: https://weibo.com/geektutu # æ¬¢è¿å…³æ³¨æˆ‘çš„ã€Œ å¾®åš ã€ã€‚

widgets:
  caidan: false  # å¼€å¯å½©è›‹ï¼Œç‚¹å‡»å±å¹•ä¼šéšæœºå¼¹å‡º 'ç‚¹ä¸ªèµ','ç•™ä¸ªè¨€'ç­‰
  busuanzi: true # å¼€å¯ä¸è’œå­ç»Ÿè®¡ https://busuanzi.ibruce.info/

# è‡ªå®šä¹‰æ¨å¹¿é“¾æ¥ï¼šå®½åº¦250ï¼Œé«˜åº¦ä¸é™ã€‚
# custom_ads:
# - link: https://s.click.taobao.com/0ZEThqv
#   img: https://img.alicdn.com/tfs/TB1QJC6dOrpK1RjSZFhXXXSdXXa-300-100.jpg
# - link: https://url.cn/5bE04oI
#   img: https://s2.ax1x.com/2020/02/12/1bns2D.jpg


ba_auto_push: true # Baidu è‡ªåŠ¨æ¨é€ï¼Œä»¥ä¸‹å‡ä¸ºå¯é€‰é…ç½®
ba_track_id: 1a0ec38c52c08db815b0046c2783b1aa # Baidu Analytics
google_analysis: UA-142641425-1 # Google Analytics

feed:
  enable: true
  limit: 0
  type: rss2
  content: false
  path: feed.xml
  icon: img/icon.png

index_rec:
- link: https://geektutu.com/post/gee.html
  name: ğŸ“˜ ä¸ƒå¤©ç”¨ Go ä»é›¶å®ç°
- link: https://geektutu.com/post/high-performance-go.html
  name: ğŸ“˜ Go è¯­è¨€é«˜æ€§èƒ½ç¼–ç¨‹
- link: https://studygolang.com
  name: ğŸ”— Go è¯­è¨€ä¸­æ–‡ç½‘