name: public blog

on:
  workflow_dispatch:
    ref: refs/heads/master
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    environment: QQ

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn build
      env:
        QQ_NAME: ${{ secrets.QQ_NAME }}
        QQ_SECRETKEY: ${{ secrets.QQ_SECRETKEY }}
        QQ_ACCESSKEY: ${{ secrets.QQ_ACCESSKEY }}
      run: |
        echo $QQ_NAME
        yarn install
        yarn update
        yarn comment
        yarn build
      # bash myscripts/qiniu_upload.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public